version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "01:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/react"
    versions:
    - ">= 17.0.a, < 17.1"
  - dependency-name: "@types/react-dom"
    versions:
    - ">= 17.0.a, < 17.1"
  - dependency-name: react-intl
    versions:
    - 5.13.1
    - 5.13.2
  - dependency-name: "@formatjs/cli"
    versions:
    - 3.1.5
    - 3.1.6
  - dependency-name: html-webpack-plugin
    versions:
    - 5.2.0
  - dependency-name: webpack
    versions:
    - 5.16.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
  - dependency-name: recharts
    versions:
    - 2.0.3
    - 2.0.4
  - dependency-name: "@alephdata/followthemoney"
    versions:
    - 2.3.1
  - dependency-name: bezier-js
    versions:
    - 4.0.3
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
