language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
jobs:
  include:
  - stage: test
    script: npm run test:prod
  - stage: build
    script: npm run build
  - stage: deploy
    script: npm run build && npm run build:docs && npm run deploy-docs && npm run semantic-release
stages:
- test
- build
- name: deploy
  if: branch = master  AND type != pull_request
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
