language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
jobs:
  include:
  - stage: lint
    script: npm run lint
  - stage: test
    script: npm run test -- --no-cache
  - stage: build
    script: npm run build
  - stage: deploy
    node_js: 11
    if: ( branch IN (alpha, master) ) AND type != pull_request
    script: npm run deploy-docs && npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
