language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
  - '10'
  - '11'

install: make install

script: make build

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
