name: build

on: [push]

jobs:
  nodejs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd js
        npm install
        npm run build
    # - name: Run the tests
    #   run: |
    #     cd js
    #     npm run test:prod && npm run lint
    - name: Publish to NPM
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      run: |
        cd js
        npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        npm run build
        npm publish
      env:
        CI: true
        NPM_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
